config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'about', to: 'home#about'
  get 'posts/new', to: 'posts#new'
  post 'posts/create', to: 'posts#create'
  get 'posts/index'
  get 'posts/:id', to: 'posts#show', as: :post
  get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
  post 'posts/:id/update', to:'posts#update', as: :update_post
  post 'posts/:id/destroy', to:'posts#destroy', as: :destroy_post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(content: params[:content])
    if @post.save
      redirect_to posts_index_url
      flash[:notice] = "投稿しました！"
    else
      render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "投稿を編集しました。"
      redirect_to posts_index_url
    else
     render :edit
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to posts_index_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_name="")
    base_title = "MiniTweet"
    if page_name.empty?
      base_title
    else
      page_name + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<% provide(:title, "Minitweetとは") %>

<div class="about-main">
  <h2>MiniTweetとは</h2>
  <p>
    SNSアプリケーションです。
    身近に起きた出来事やその時の気持ちを投稿し、他のユーザーと楽しくシェアできます。
  </p>
  <img class="about-img" src="/about.png">
</div>

app/views/home/top.html.erb
<% provide(:title, "トップ") %>

<div class="main top-main">
  <div class="top-message">
    <h2>ミニTWEETへようこそ！</h2>
    <p>楽しく呟いて世界中と共有しよう</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="header-logo">
    <%= link_to "MiniTweet", root_path %>
  </div>
  <ul class="header-menus">
    <li><%= link_to "MiniTweetについて", about_path %></a></li>
    <li><%= link_to "投稿一覧", posts_index_path %></li>
    <li><%= link_to "新規投稿", posts_new_path %></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <div class="flash"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿編集</h1>
    <%= form_tag update_post_path do %>
      <div class="form">
         <div class="form-body">
          <% @post.errors.full_messages.each do |message| %>
            <div class="form-error"><%= message %></div>
          <% end %>
          <textarea name="content"><%= @post.content %></textarea>
          <input type="submit", value="保存">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "投稿") %>

<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <%= link_to post.content, post_path(post.id) %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "新規投稿") %>

<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">新規投稿</h1>
    <%= form_tag posts_create_path do %>
      <div class="form">
        <div class="form-body">
          <% @post.errors.full_messages each do |message| %>
            <div class="form-error"><%= message %></div>
          <% end %>
          <textarea name="content"></textarea>
          <input type="submit" value="投稿">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <p>投稿詳細ページ：投稿IDは<%= @post.id %></p>
      <p><%= @post.content %></p>
      <div class="post-menus">
        <%= link_to "編集", edit_post_path(@post.id), class: "post_edit_button" %>
        <%= link_to "削除", destroy_post_path(@post.id), method: :post, class: "post_delete_button" %>
      </div>
    </div>
  </div>
</div>